on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --bare ${{ github.repositoryUrl }} .
          git push --mirror https://${{ secrets.CODING_TOKEN }}@e.coding.net/xing2000/aria2rc
