on:
  push:
    paths:
      - .github/workflows/update-aria2c.yml
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 下载源码
        run: git clone --depth=1 ${{ github.repositoryUrl }} .

      - name: 下载aria2c
        run: update-aria2c.sh

      - name: 检查变化
        run: '[[ $(git status -s) ]]'

      - name: 部署
        run: |
          git add .
          git config user.name ${{ github.event.pusher.name }}
          git config user.email ${{ github.event.pusher.email }}
          git commit -m '自动更新'
          git push
