on:
  push:
    paths:
      - .github/workflows/update-aria2c.yml
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - run: |
          wget api.github.com/repos/aria2/aria2/releases?per_page=1 -O releases
          for arch in 32bit 64bit; do
            wget -qO '/tmp/aria2.zip' \
              $(jq -r ".[0].assets[].browser_download_url | select(contains(\"win-$arch\"))" releases)
            unzip '/tmp/aria2.zip' '*/aria2c.exe' -d '/tmp'
            mv /tmp/aria2*/aria2c.exe aria2c.exe.$arch
            rm -rf /tmp/aria2*
          done
          rm releases
          git init
          git add .
          git config user.name star2000
          git config user.email i@star2000.work
          git commit -m '自动更新'
          git push -f https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} master:exe
